POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com"
}

###

GET http://localhost:3333/invites/f3b3599b-f6cb-4fde-a924-295a54254bdf

###

GET http://localhost:3333/subscribers/f3b3599b-f6cb-4fde-a924-295a54254bdf/ranking/clicks